# Generated by Django 3.0.8 on 2020-08-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('web_site', models.URLField(max_length=100, verbose_name='Web site')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Date published')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('rating', models.CharField(max_length=50, verbose_name='Rating')),
                ('reviews', models.CharField(max_length=50, verbose_name='Reviews')),
                ('comment', models.TextField(max_length=300, verbose_name='Comment')),
                ('Performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performer.Performer')),
            ],
            options={
                'verbose_name': 'Performer',
                'verbose_name_plural': 'Performers',
            },
        ),
    ]
