# Generated by Django 3.0.8 on 2020-08-30 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('rating', models.CharField(max_length=50, verbose_name='Rating')),
                ('reviews', models.CharField(max_length=50, verbose_name='Reviews')),
                ('comment', models.TextField(max_length=300, verbose_name='Comment')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AlterModelOptions(
            name='performer',
            options={'verbose_name': 'Performer', 'verbose_name_plural': 'Performers'},
        ),
        migrations.RemoveField(
            model_name='performer',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='performer',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Change'),
        ),
        migrations.AddField(
            model_name='performer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='Performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performer.Performer'),
        ),
    ]
