# Generated by Django 3.0.8 on 2020-08-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0002_auto_20200830_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AlterField(
            model_name='review',
            name='reviews',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Reviews'),
        ),
    ]
