# Generated by Django 3.0.8 on 2020-08-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0003_auto_20200830_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=1, verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviews',
            field=models.TextField(max_length=300, verbose_name='Reviews'),
        ),
    ]
