# Generated by Django 3.0.8 on 2020-08-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0005_auto_20200830_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='description',
            field=models.TextField(max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='performer',
            name='option',
            field=models.CharField(max_length=30, null=True, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='performer',
            name='phone',
            field=models.CharField(max_length=16, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='performer',
            name='since',
            field=models.CharField(max_length=4, null=True, verbose_name='Since'),
        ),
        migrations.AddField(
            model_name='performer',
            name='work_zone',
            field=models.CharField(max_length=30, null=True, verbose_name='Work zone'),
        ),
    ]
