# Generated by Django 3.0.8 on 2020-08-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0006_auto_20200830_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Performer',
            new_name='performer',
        ),
        migrations.AddField(
            model_name='performer',
            name='specialization',
            field=models.CharField(default=True, max_length=50, verbose_name='Specialization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performer',
            name='create_date',
            field=models.DateTimeField(verbose_name='Create'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='description',
            field=models.TextField(default=True, max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performer',
            name='option',
            field=models.CharField(default=True, max_length=30, verbose_name='Option'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performer',
            name='phone',
            field=models.CharField(default=True, max_length=16, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performer',
            name='since',
            field=models.CharField(default=True, max_length=4, verbose_name='Since'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performer',
            name='work_zone',
            field=models.CharField(default=True, max_length=30, verbose_name='Work zone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(verbose_name='Create'),
        ),
    ]
