# Generated by Django 3.0.8 on 2020-08-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0007_auto_20200830_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('create_date', models.DateTimeField(verbose_name='Create')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change')),
            ],
        ),
    ]
