# Generated by Django 3.0.8 on 2020-08-30 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0008_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performer.Specialization'),
        ),
    ]
