# Generated by Django 3.0.8 on 2020-08-31 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200830_1658'),
        ('performer', '0009_auto_20200830_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='work_zone',
        ),
        migrations.AddField(
            model_name='performer',
            name='city',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performer',
            name='contry',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.Contry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performer',
            name='provinces',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.Provinces'),
            preserve_default=False,
        ),
    ]
