# Generated by Django 3.0.8 on 2020-08-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0010_auto_20200830_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default=True, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
