# Generated by Django 3.0.8 on 2020-09-28 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200830_1658'),
        ('performer', '0011_review_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performer',
            options={'ordering': ['name'], 'verbose_name': 'Performer', 'verbose_name_plural': 'Performers'},
        ),
        migrations.RemoveField(
            model_name='performer',
            name='city',
        ),
        migrations.AddField(
            model_name='performer',
            name='city',
            field=models.ManyToManyField(to='main.City'),
        ),
        migrations.RemoveField(
            model_name='performer',
            name='contry',
        ),
        migrations.AddField(
            model_name='performer',
            name='contry',
            field=models.ManyToManyField(to='main.Contry'),
        ),
        migrations.RemoveField(
            model_name='performer',
            name='provinces',
        ),
        migrations.AddField(
            model_name='performer',
            name='provinces',
            field=models.ManyToManyField(to='main.Provinces'),
        ),
        migrations.RemoveField(
            model_name='performer',
            name='specialization',
        ),
        migrations.AddField(
            model_name='performer',
            name='specialization',
            field=models.ManyToManyField(to='performer.Specialization'),
        ),
        migrations.AlterField(
            model_name='review',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performer.Performer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], decimal_places=1, default=1, max_digits=2, verbose_name='Rating'),
        ),
    ]
