# Generated by Django 3.0.8 on 2020-09-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200927_2335'),
        ('performer', '0012_auto_20200927_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='contry',
        ),
        migrations.AddField(
            model_name='performer',
            name='country',
            field=models.ManyToManyField(to='main.Country'),
        ),
    ]
