# Generated by Django 3.0.8 on 2020-10-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0014_auto_20201004_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='performer.Group'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(help_text='Enter field documentation', max_length=50, verbose_name='Name'),
        ),
    ]
