# Generated by Django 3.0.8 on 2020-10-12 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0015_auto_20201011_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_specialization', to='performer.Group'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(help_text='Test', max_length=50, verbose_name='Name'),
        ),
    ]
