# Generated by Django 3.0.8 on 2020-10-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0016_auto_20201012_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(help_text='///', max_length=50, verbose_name='Name'),
        ),
    ]
