# Generated by Django 3.0.8 on 2020-10-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0017_auto_20201012_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='specialization',
            field=models.ManyToManyField(related_name='specializations', to='performer.Specialization'),
        ),
    ]
