# Generated by Django 3.0.8 on 2020-10-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0018_auto_20201012_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='city',
            new_name='cities',
        ),
        migrations.RenameField(
            model_name='performer',
            old_name='specialization',
            new_name='specializations',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='performer',
            new_name='performers',
        ),
        migrations.RenameField(
            model_name='specialization',
            old_name='group',
            new_name='groups',
        ),
    ]
