# Generated by Django 3.0.8 on 2020-10-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0019_auto_20201012_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='specializations',
            field=models.ManyToManyField(related_name='performers', to='performer.Specialization'),
        ),
    ]
