# Generated by Django 3.0.8 on 2020-10-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0020_auto_20201013_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='specializations',
            field=models.ManyToManyField(to='performer.Specialization'),
        ),
    ]
