# Generated by Django 3.0.8 on 2020-10-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0022_auto_20201014_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(help_text='///', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(help_text='///', max_length=10, verbose_name='Number'),
        ),
    ]
