# Generated by Django 3.0.8 on 2020-10-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0023_auto_20201014_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='email',
        ),
        migrations.AddField(
            model_name='performer',
            name='email',
            field=models.ManyToManyField(to='performer.Email'),
        ),
        migrations.RemoveField(
            model_name='performer',
            name='phone',
        ),
        migrations.AddField(
            model_name='performer',
            name='phone',
            field=models.ManyToManyField(to='performer.Phone'),
        ),
    ]
