# Generated by Django 3.0.8 on 2020-10-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0024_auto_20201014_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='phone',
            new_name='phones',
        ),
    ]
