# Generated by Django 3.0.8 on 2020-08-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_city_contry_provinces'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Сities'},
        ),
        migrations.AlterModelOptions(
            name='contry',
            options={'verbose_name': 'Contry', 'verbose_name_plural': 'Contry'},
        ),
        migrations.AlterModelOptions(
            name='provinces',
            options={'verbose_name': 'Provinces', 'verbose_name_plural': 'Provinces'},
        ),
    ]
