# Generated by Django 3.0.8 on 2020-09-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200830_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='provinces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Provinces'),
        ),
        migrations.AddField(
            model_name='provinces',
            name='contry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Contry'),
        ),
    ]
