# Generated by Django 3.0.8 on 2020-09-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200927_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contry',
            options={},
        ),
        migrations.RemoveField(
            model_name='provinces',
            name='contry',
        ),
    ]
