# Generated by Django 3.0.8 on 2020-09-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200927_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinces',
            name='contry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Contry'),
        ),
    ]
