# Generated by Django 3.0.8 on 2020-09-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0012_auto_20200927_2253'),
        ('main', '0007_provinces_contry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contry',
            new_name='Country',
        ),
        migrations.AlterModelOptions(
            name='provinces',
            options={},
        ),
        migrations.RenameField(
            model_name='provinces',
            old_name='contry',
            new_name='country',
        ),
    ]
