# Generated by Django 3.0.8 on 2020-10-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
