# Generated by Django 3.0.8 on 2020-08-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Messages',
        ),
    ]
