# Generated by Django 3.0.8 on 2020-08-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200823_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='created',
        ),
    ]
